### ISSUE TITLE
dynect role

### ISSUE THREAD

**Issue by pawel-yesware** [yetu/ansible-plugins-library#1]
Hi,
I wonder if you could publish dynect role that uses this module?
Thanks

**Comment by alop** [comment]
Maybe a brief example in the readme?

**Comment by pawel-yesware** [comment]
Actually I was able to figure it out but i'm having issues with it...

```
  - name: dynect
    hosts: local
    connection: local
    gather_facts: False
    tasks:
      - name: dupa
        local_action: 
          module: dynect 
          customer_name: CUSTOMER
          username: LOGIN
          password: PASSWORD
          rtype: CNAME 
          domain: sample.com
          hostname: subdomain
          linkname: google.com
```

but i get this kind of error

`task path: /Users/pkilian/yesware/RAW/ansible/test.yml:74
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Status is not success. Record info='{u'status': u'failure', u'data': {}, u'job_id': 2247800111, u'msgs': [{u'INFO': u'action: Could not determine zone', u'SOURCE': u'BLL', u'ERR_CD': u'NOT_FOUND', u'LVL': u'ERROR'}, {u'INFO': u'add_node: Could not determine zone', u'SOURCE': u'BLL', u'ERR_CD': None, u'LVL': u'INFO'}]}'"}`
